### ISSUE TITLE
TENplay missing shows

### ISSUE THREAD

**Issue by unlocKing** [xbmc-catchuptv-au/plugin.video.catchuptv.au.ten#1104]
In the 'TV shows' sections, you can see Australian Survivor... but once you click into it, there are no shows, completely empty.

However on the TEN website all the shows are availableConfused

It's the same for most sections.

Only reliable section working is 'Featured'.

`12:19:07 T:7752  NOTICE: [xbmcswift2] Request for "/" matches rule for function "menu"
12:19:07 T:7752 WARNING: CPythonInvoker(51, C:\Users\j\AppData\Roaming\Kodi\addons\plugin.video.catchuptv.au.ten\default.py)​: the python script "C:\Users\j\AppData\Roaming\Kodi\addons\plugin.video.catchuptv.au.ten\default.py​" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcaddon::Addon,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem
12:19:13 T:9672  NOTICE: [xbmcswift2] Request for "/shows/tvshows" matches rule for function "showlist"
12:19:34 T:9672 WARNING: CPythonInvoker(52, C:\Users\j\AppData\Roaming\Kodi\addons\plugin.video.catchuptv.au.ten\default.py)​: the python script "C:\Users\j\AppData\Roaming\Kodi\addons\plugin.video.catchuptv.au.ten\default.py​" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcaddon::Addon,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem,class XBMCAddon::xbmcgui::ListItem
12:19:38 T:2300  NOTICE: [xbmcswift2] Request for "/videos/all%3Dtv_show%253AAustralian%2BSurvivor%26all%3Dvideo_type_long_form%253AFull%2B​Episodes%26all%3Dvideo_type_long_form%253AFull%2BEpisode/0" matches rule for function "videolist"
12:19:39 T:9980   ERROR: CImageLoader::DoWork - Direct texture file loading failed for special://skin/backgrounds/addons.jpg
12:19:39 T:2300 WARNING: CPythonInvoker(53, C:\Users\j\AppData\Roaming\Kodi\addons\plugin.video.catchuptv.au.ten\default.py)​: the python script "C:\Users\j\AppData\Roaming\Kodi\addons\plugin.video.catchuptv.au.ten\default.py​" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcaddon::Addon
12:20:12 T:13288  NOTICE: [xbmcswift2] Request for "/videos/all%3Dtv_show%253AThe%2BBachelor%2BAustralia%26all%3Dvideo_type_long_form%253AFu​ll%2BEpisodes%26all%3Dvideo_type_long_form%253AFull%2BEpisode/0" matches rule for function "videolist"
12:20:12 T:11268   ERROR: CImageLoader::DoWork - Direct texture file loading failed for special://skin/backgrounds/addons.jpg
12:20:13 T:13288 WARNING: CPythonInvoker(54, C:\Users\j\AppData\Roaming\Kodi\addons\plugin.video.catchuptv.au.ten\default.py)​: the python script "C:\Users\j\AppData\Roaming\Kodi\addons\plugin.video.catchuptv.au.ten\default.py​" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcaddon::Addon`

**Comment by adammw** [comment]
It's subtle, but basically, whoever wrote the query for Australian Survivor put "Full Episodes" in instead of "Full Episode", which due to exact matching, showed no shows. I've added a patch to filter out this typo in v0.5.13, but I might have to switch to a different feed in the future.
