### ISSUE TITLE
Script Failed

### ISSUE THREAD

**Issue by Qwertyfly** [xbmc-catchuptv-au/plugin.video.catchuptv.au.ten#445]
been using this add-on daily for a long time now.
today it does not work.
version 0.5.7
I see this was released 14 hours ago.

looks like is has something to do with the rollbar addition.

any ideas???

thanks.

part of log:

"
13:49:54 T:6060   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named rollbar
                                            Traceback (most recent call last):
                                              File "C:\Users\Qwerty\AppData\Roaming\Kodi\addons\plugin.video.catchuptv.au.ten\default.py", line 35, in <module>
                                                from networktenaddon import Addon
                                              File "C:\Users\Qwerty\AppData\Roaming\Kodi\addons\plugin.video.catchuptv.au.ten\resources\lib\networktenaddon\__init__.py", line 30, in <module>
                                                from utils import Utils
                                              File "C:\Users\Qwerty\AppData\Roaming\Kodi\addons\plugin.video.catchuptv.au.ten\resources\lib\networktenaddon\utils.py", line 30, in <module>
                                                from issue_reporter import IssueReporter
                                              File "C:\Users\Qwerty\AppData\Roaming\Kodi\addons\plugin.video.catchuptv.au.ten\resources\lib\issue_reporter.py", line 31, in <module>
                                                import rollbar
                                            ImportError: No module named rollbar
                                            -->End of Python script error report<--
13:49:54 T:5896   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
13:49:54 T:6060    INFO: Python script stopped
13:49:54 T:6060   DEBUG: Thread LanguageInvoker 6060 terminating
13:49:54 T:5896   DEBUG:  XFILE::CPluginDirectory::WaitOnScriptResult - plugin exited prematurely - terminating
13:49:54 T:5896   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.catchuptv.au.ten/
13:49:54 T:5896   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptv.au.ten/) failed
13:49:54 T:5896   DEBUG: CGUIMediaWindow::GetDirectory ()
13:49:54 T:5896   DEBUG:   ParentPath = [plugin://plugin.video.catchuptv.au.ten/]
13:49:54 T:8012  NOTICE: Thread BackgroundLoader start, auto delete: false
13:49:54 T:5896   DEBUG: ------ Window Deinit (DialogAddonInfo.xml) ------
13:49:54 T:8012   DEBUG: Thread BackgroundLoader 8012 terminating
13:49:56 T:1048   DEBUG: webserver: request received for /jsonrpc
13:49:58 T:5896   DEBUG: Previous line repeats 1 times.
13:49:58 T:5896    INFO: XCURL::DllLibCurlGlobal::CheckIdle - Closing session to https://github.com (easy=153D0048, multi=00000000)
"

**Comment by adammw** [comment]
Whoops, sorry about that. Forgot to add it to the addons.xml listing in the repo. I've updated it now manually but you'll need to install it yourself as it doesn't seem to take notice without a version change. Go into Get Adddons > Add-on libraries > Rollbar Issue Reporter and install that, then it should start working again.

**Comment by Qwertyfly** [comment]
I downgraded to previous version. 
It did an update today and installed rollbar. 
Thanks for fixing it so fast. 
Better then that, thanks for the add on!


Tristan...
